import Header from './_components/Header'
import './globals.scss'
import { Maven_Pro } from 'next/font/google'

const appFont = Maven_Pro({ subsets: ['latin'] })

export const metadata = {
  title: "liel's portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className={appFont.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
